### ISSUE TITLE
SkyQ not working with 2021.12

### ISSUE THREAD

**Issue by Zahnweh** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#77]
After upgrading to 2021.12 my SkyQ was not responding anymore. Checking the installation produced an error:

Platform error media_player.skyq - cannot import name 'HTTP_OK' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py) 

As there were other issues I had to restore 2021.11. But let me know If you need more info.

**Comment by RogerSelwyn** [comment]
What version of the SkyQ integration are you using?

**Comment by RogerSelwyn** [comment]
As far as I can see the latest version v2.7.5 does not use HTTP_OK at all anymore, so this error would surprise me. All http calls are done via pyskyqremote which also does not use that contstant (and wouldn't import from HA anyway since it is HA independent.

Please upgrade to the latest version (which works against 2021.11) and retry the upgrade.

**Comment by Zahnweh** [comment]
Thanks for you quick reply. I wasn't on 2.7.5 but I have just installed it and will try the upgrade to HA 2021.12 again as soon as the other issues I ran into have been solved.

**Comment by RogerSelwyn** [comment]
Latest version of SkyQ integration is a known fix.
