### ISSUE TITLE
[BUG] Failed to setup: Import error after update to 2.11.12

### ISSUE THREAD

**Issue by ianfretwell** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#181]
### Describe the bug

Logs show:-

Logger: homeassistant.config_entries
Source: config_entries.py:609
First occurred: 15:04:22 (4 occurrences)
Last logged: 15:12:34

Error importing platform config_flow from integration skyq to set up skyq configuration entry: cannot import name 'ssdp' from 'homeassistant.helpers.service_info' (/usr/src/homeassistant/homeassistant/helpers/service_info/__init__.py)

### To reproduce

Upgrade to v2.11.12

### Expected bahavior

No error

### What version of SkyQ has the issue?

2.11.12

### What was the last working version of Sky Q Integration?

2.11.11

### What version of Home Assistant Core has the issue?

2025.1.4

### Configuration type

UI

### Configuration UI

```jsono

```

### Configuration YAML

```yaml

```

### Additional information

```txt

```

**Comment by RogerSelwyn** [comment]
You did of course notice in the release notes that it requires 2025.2.0?

**Comment by ianfretwell** [comment]
Ah - I did not, but of course who looks at those when HACS just pops up with the update available?

Not a problem though - so thanks for the heads-up!

**Comment by rchiileea** [comment]
I had the same issue, a quick reboot of system (not restart fixed it for me btw) I know this is closed but i thought I would mention that, always a good option to reboot system rather than restart if anything is wrong first and then report... thanks for the integration btw.
